name: "📘 Repository template"
description: A template mimicking GitHub visual identity and specially crafted for repositories.
examples:
  default: https://github.com/lowlighter/metrics/blob/examples/metrics.repository.svg
index: 1
supports:
  - repository
formats:
  - svg
  - png
  - jpeg
  - json
